name: image_processing_plugin
description: "A Flutter plugin for image processing tasks including face detection, brightness checks, and photo filters."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_face_detection: ^0.10.0
  image: ^4.1.3
  flutter_image_filters: ^0.0.28
  path_provider: ^2.1.1 # <--- ADD THIS LINE

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.image_processing.image_processing_plugin
        pluginClass: ImageProcessingPlugin
      ios:
        pluginClass: ImageProcessingPlugin
